services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  bankaccount.api:
    image: bankaccountapi
    ports:
      - 7001:8080
    build:
      context: .
      dockerfile: src/Services/BankAccount/BankAccount.Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
  topup.api:
    image: topupapi
    ports:
      - 7002:8080
    build:
      context: .
      dockerfile: src/Services/TopUp/TopUp.Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - bankaccount.api
